import string, itertools, hashlib
text_file = open('hashes&randomseeds.txt', 'w') #create text file...
abc_lowercase = string.ascii_lowercase #lowercase alphabet...
abc_uppercase = string.ascii_uppercase #uppercase alphabet... 
alphabet_lowercase = list(abc_lowercase) #create a list of lowercase alphabet...
alphabet_uppercase = list(abc_uppercase) #create a list of uppercase alphabet...
merge_alphabet = alphabet_lowercase + alphabet_uppercase #both lowercase and uppercase alphabet...
numbers_list = list(range(0,25)) #Create a list of number between 0 to 24...
hashes_and_seeds = []
for seed in itertools.combinations(merge_alphabet, 32): #combinations of 32 letters(lowercase and uppercase)... 
    for num in numbers_list: 
         pure_random_seed = str(num) + '_' + str(seed) #creating the random seed...
         random_seed = pure_random_seed.replace(")", "").replace("(", "").replace("'", "").replace(",", "").replace(" ", "") #remove all the unnneeded strings...
         hash_seed = hashlib.sha256(random_seed.encode('utf-8')).hexdigest() #hash_random_seed...
         text_file.write(hash_seed + ' : ' + random_seed + '\n')
text_file.close() #close text file...         
